### PR TITLE
Add support for HifiBerry sound cards

### PR DESCRIPTION
**Pull request by clandry**
Add new category to separate hardware driver configuration blocks from "Programs" category. Add support for HifiBerry sound card configuration block and move the existing IQaudIO configuration block to new "Drivers" category. Improve /boot/config.txt manipulation when disabling on-board sound card

### CODE REVIEW

**Comment by davidferguson** [comment]
Sorry for the delay in responding to this, but could you please open pull requests for block in the separate blocks repo: [davidferguson/pibakery-blocks](https://github.com/davidferguson/pibakery-blocks)

**Comment by clandry** [comment]
Sure, had opened the pull request here due to the category changes though, should I split it into 2 pull requests, one for this repo and one for the pibakery-blocks repo?

**Comment by davidferguson** [comment]
It's actually just categories.json and info.json (which are both [also in the pibakery-blocks repo](https://github.com/davidferguson/pibakery-blocks/blob/master/categories.json)) that you need to alter - PiBakery will do the rest for you.

**Comment by clandry** [comment]
OK, I had made the other edits to avoid the slight delay where it showed the hard-coded values before it loaded the categories.json

**Pull request closed without merging**
