### PR TITLE
add git clone

### PR DESCRIPTION
**Pull request by acrogenesis**
Added the ability to git clone a repository. Wasn't sure to add it on Network or Other

### CODE REVIEW

**Comment by evanwaltersdev** [comment]
I like this

**Comment by acrogenesis** [comment]
What do you think @davidferguson

**Comment by 0E800** [comment]
Curious as to the lack of development / community additions going on with this most excellent tool.

Thank you @acrogenesis ,  using it.

**Comment by ashleycawley** [comment]
@0E800 That's because the main program/branch in maintained by a young lad whos life is very busy with education, exams and many other things likely more important to him than just PiBakery. Encourage others to get involved with its development and we lets do what we can to help! :-)

**Comment by maskaravivek** [comment]
It would be great if the project could have more maintainers who could actively manage this amazing project. :)

**Comment by jedahan** [comment]
I merged all the open PRs into a fork. Totally untested - I just made sure I could `npm run build-mac` and open the app, but it seems alright for now. https://github.com/baculus-buoy/pibakery/releases/tag/v0.3.9

**Comment by davidferguson** [comment]
Apologies for the lack of activity, I'm hoping to be more active with PiBakery from now on (and there may be some exciting developments coming!).

Block submissions should be made to [davidferguson/pibakery-blocks](https://github.com/davidferguson/pibakery-blocks) rather than this repo.

**Pull request closed without merging**
